# Config file for Air (https://github.com/cosmtrek/air)
[build]
  bin = "tmp/main" # Binary name
  cmd = "go build -buildvcs=false -o tmp/main ./..." # Command to build your app
  include_ext = ["go", "tpl", "tmpl", "html"] # Extensions to watch
  exclude_dir = ["vendor", "tmp", ".git", "node_modules"] # Directories to ignore
  exclude_file = [] # Specific files to ignore
  follow_symlink = true # Follow symlinks
  full_reload = false # Enable full reload
  include_dir = ["."] # Directories to watch

[log]
  level = "debug"

[serve]
  cmd = "tmp/main" # Command to run your app
  delay = "500ms" # Delay before starting the app after a change
  grace = "100ms" # Grace period before killing the app after a change
  ignore_error = false
  shell = "sh" # Shell to use
  kill_signal = "INT" # Signal to kill the app

[watch]
  main = "./main.go" # Main file to watch
  dir = "." # Directory to watch
