# version: '3.8'

services:
  app:
    build: .
    command: air
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ".:/app"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3000

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
