# version: '3.8'

services:

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=sqlite
      - DB_SQLITE_VACUUM_ON_STARTUP=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=foo
      - N8N_BASIC_AUTH_PASSWORD=bar
      - N8N_HOST=hoffmanc.com
      - N8N_PORT=hoffmanc.com
    volumes:
      - n8n-data:/home/node/.n8n
    restart: unless-stopped

  envoy:
    image: envoyproxy/envoy:v1.20.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./ssl:/etc/envoy/ssl  # Mount the directory containing your SSL certificate and key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - n8n
    restart: unless-stopped

volumes:
  n8n-data:
